/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package findjob;

/**
 *
 * @author BusraGural
 */
public class AccountPageUI extends javax.swing.JFrame {

    /**
     * Creates new form AccountPageUI
     */
    public AccountPageUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        educationLabel = new javax.swing.JLabel();
        educationPanel = new javax.swing.JPanel();
        schoolNameField = new javax.swing.JTextField();
        departmentNameField = new javax.swing.JTextField();
        startDateField = new javax.swing.JTextField();
        finishDateField = new javax.swing.JTextField();
        gradeField = new javax.swing.JTextField();
        gradeLabel = new javax.swing.JLabel();
        experinceLabel = new javax.swing.JLabel();
        experiencePanel = new javax.swing.JPanel();
        schoolNameField1 = new javax.swing.JTextField();
        departmentNameField2 = new javax.swing.JTextField();
        startField = new javax.swing.JTextField();
        finishField = new javax.swing.JTextField();
        jobField = new javax.swing.JTextField();
        certifLabel = new javax.swing.JLabel();
        certifPanel = new javax.swing.JPanel();
        certifNameField = new javax.swing.JTextField();
        cstartField = new javax.swing.JTextField();
        cfinishField = new javax.swing.JTextField();
        departmentField = new javax.swing.JTextField();
        appLabel = new javax.swing.JLabel();
        appPanel = new javax.swing.JPanel();
        advTitle = new javax.swing.JTextField();
        advOwnerField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 231, 231));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel4.setBackground(new java.awt.Color(234, 231, 231));

        imagePanel.setBackground(new java.awt.Color(118, 179, 157));

        editButton.setBackground(new java.awt.Color(231, 231, 231));
        editButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        editButton.setForeground(new java.awt.Color(118, 179, 157));
        editButton.setText("Düzenle");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton)
                .addContainerGap())
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editButton)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        nameLabel.setBackground(new java.awt.Color(234, 231, 231));
        nameLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(40, 55, 57));
        nameLabel.setText("AD SOYAD");

        educationLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        educationLabel.setForeground(new java.awt.Color(40, 55, 57));
        educationLabel.setText("Eğitim");

        educationPanel.setBackground(new java.awt.Color(231, 231, 231));
        educationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        schoolNameField.setBackground(new java.awt.Color(231, 231, 231));
        schoolNameField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        schoolNameField.setForeground(new java.awt.Color(40, 55, 57));
        schoolNameField.setText("Üniversite Adı");
        schoolNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolNameFieldActionPerformed(evt);
            }
        });

        departmentNameField.setBackground(new java.awt.Color(231, 231, 231));
        departmentNameField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        departmentNameField.setForeground(new java.awt.Color(40, 55, 57));
        departmentNameField.setText("Bölüm Adı");
        departmentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentNameFieldActionPerformed(evt);
            }
        });

        startDateField.setBackground(new java.awt.Color(231, 231, 231));
        startDateField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        startDateField.setForeground(new java.awt.Color(40, 55, 57));
        startDateField.setText("Başlangıç Tarihi");
        startDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateFieldActionPerformed(evt);
            }
        });

        finishDateField.setBackground(new java.awt.Color(231, 231, 231));
        finishDateField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        finishDateField.setForeground(new java.awt.Color(40, 55, 57));
        finishDateField.setText("Bitiş Tarihi");
        finishDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishDateFieldActionPerformed(evt);
            }
        });

        gradeField.setBackground(new java.awt.Color(231, 231, 231));
        gradeField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        gradeField.setForeground(new java.awt.Color(40, 55, 57));
        gradeField.setText("3.8");
        gradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeFieldActionPerformed(evt);
            }
        });

        gradeLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(39, 41, 50));
        gradeLabel.setText("Not Ortalaması:");

        javax.swing.GroupLayout educationPanelLayout = new javax.swing.GroupLayout(educationPanel);
        educationPanel.setLayout(educationPanelLayout);
        educationPanelLayout.setHorizontalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addComponent(schoolNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(finishDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(gradeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gradeField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        educationPanelLayout.setVerticalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeLabel)
                    .addComponent(gradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        experinceLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        experinceLabel.setForeground(new java.awt.Color(40, 55, 57));
        experinceLabel.setText("Deneyim");

        experiencePanel.setBackground(new java.awt.Color(231, 231, 231));
        experiencePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        schoolNameField1.setBackground(new java.awt.Color(231, 231, 231));
        schoolNameField1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        schoolNameField1.setForeground(new java.awt.Color(40, 55, 57));
        schoolNameField1.setText("Kurum Adı");
        schoolNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolNameField1ActionPerformed(evt);
            }
        });

        departmentNameField2.setBackground(new java.awt.Color(231, 231, 231));
        departmentNameField2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        departmentNameField2.setForeground(new java.awt.Color(40, 55, 57));
        departmentNameField2.setText("Departman");
        departmentNameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentNameField2ActionPerformed(evt);
            }
        });

        startField.setBackground(new java.awt.Color(231, 231, 231));
        startField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        startField.setForeground(new java.awt.Color(40, 55, 57));
        startField.setText("Başlangıç Tarihi");
        startField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startFieldActionPerformed(evt);
            }
        });

        finishField.setBackground(new java.awt.Color(231, 231, 231));
        finishField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        finishField.setForeground(new java.awt.Color(40, 55, 57));
        finishField.setText("Bitiş Tarihi");
        finishField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishFieldActionPerformed(evt);
            }
        });

        jobField.setBackground(new java.awt.Color(231, 231, 231));
        jobField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jobField.setForeground(new java.awt.Color(40, 55, 57));
        jobField.setText("Meslek Adı");
        jobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout experiencePanelLayout = new javax.swing.GroupLayout(experiencePanel);
        experiencePanel.setLayout(experiencePanelLayout);
        experiencePanelLayout.setHorizontalGroup(
            experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experiencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(experiencePanelLayout.createSequentialGroup()
                        .addComponent(schoolNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(departmentNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(finishField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(experiencePanelLayout.createSequentialGroup()
                        .addComponent(jobField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        experiencePanelLayout.setVerticalGroup(
            experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experiencePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        certifLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        certifLabel.setForeground(new java.awt.Color(40, 55, 57));
        certifLabel.setText("Sertifikalar");

        certifPanel.setBackground(new java.awt.Color(231, 231, 231));
        certifPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        certifNameField.setBackground(new java.awt.Color(231, 231, 231));
        certifNameField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        certifNameField.setForeground(new java.awt.Color(40, 55, 57));
        certifNameField.setText("Sertifika Adı");
        certifNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certifNameFieldActionPerformed(evt);
            }
        });

        cstartField.setBackground(new java.awt.Color(231, 231, 231));
        cstartField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cstartField.setForeground(new java.awt.Color(40, 55, 57));
        cstartField.setText("Başlangıç Tarihi");
        cstartField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstartFieldActionPerformed(evt);
            }
        });

        cfinishField.setBackground(new java.awt.Color(231, 231, 231));
        cfinishField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cfinishField.setForeground(new java.awt.Color(40, 55, 57));
        cfinishField.setText("Bitiş Tarihi");
        cfinishField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfinishFieldActionPerformed(evt);
            }
        });

        departmentField.setBackground(new java.awt.Color(231, 231, 231));
        departmentField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        departmentField.setForeground(new java.awt.Color(40, 55, 57));
        departmentField.setText("Alındığı Yer");
        departmentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout certifPanelLayout = new javax.swing.GroupLayout(certifPanel);
        certifPanel.setLayout(certifPanelLayout);
        certifPanelLayout.setHorizontalGroup(
            certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(certifPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(certifPanelLayout.createSequentialGroup()
                        .addComponent(certifNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addComponent(cstartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cfinishField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(certifPanelLayout.createSequentialGroup()
                        .addComponent(departmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        certifPanelLayout.setVerticalGroup(
            certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(certifPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certifNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cstartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cfinishField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        appLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        appLabel.setForeground(new java.awt.Color(40, 55, 57));
        appLabel.setText("Başvurularım");

        appPanel.setBackground(new java.awt.Color(231, 231, 231));
        appPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        advTitle.setBackground(new java.awt.Color(231, 231, 231));
        advTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        advTitle.setForeground(new java.awt.Color(40, 55, 57));
        advTitle.setText("İlan Başlığı");
        advTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advTitleActionPerformed(evt);
            }
        });

        advOwnerField.setBackground(new java.awt.Color(231, 231, 231));
        advOwnerField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        advOwnerField.setForeground(new java.awt.Color(40, 55, 57));
        advOwnerField.setText("Kurum");
        advOwnerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advOwnerFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout appPanelLayout = new javax.swing.GroupLayout(appPanel);
        appPanel.setLayout(appPanelLayout);
        appPanelLayout.setHorizontalGroup(
            appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(advOwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        appPanelLayout.setVerticalGroup(
            appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advOwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(appPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(appLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(certifPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(experiencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(experinceLabel))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLabel)
                                .addComponent(educationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(educationLabel)))
                        .addComponent(certifLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(131, 131, 131))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(educationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(educationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(experinceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(experiencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(certifLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(certifPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(appLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schoolNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolNameFieldActionPerformed

    private void departmentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentNameFieldActionPerformed

    private void startDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateFieldActionPerformed

    private void finishDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishDateFieldActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void gradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeFieldActionPerformed

    private void schoolNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolNameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolNameField1ActionPerformed

    private void departmentNameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentNameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentNameField2ActionPerformed

    private void startFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startFieldActionPerformed

    private void finishFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishFieldActionPerformed

    private void jobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobFieldActionPerformed

    private void certifNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certifNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certifNameFieldActionPerformed

    private void cstartFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstartFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cstartFieldActionPerformed

    private void cfinishFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfinishFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cfinishFieldActionPerformed

    private void departmentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentFieldActionPerformed

    private void advTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advTitleActionPerformed

    private void advOwnerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advOwnerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advOwnerFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountPageUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advOwnerField;
    private javax.swing.JTextField advTitle;
    private javax.swing.JLabel appLabel;
    private javax.swing.JPanel appPanel;
    private javax.swing.JLabel certifLabel;
    private javax.swing.JTextField certifNameField;
    private javax.swing.JPanel certifPanel;
    private javax.swing.JTextField cfinishField;
    private javax.swing.JTextField cstartField;
    private javax.swing.JTextField departmentField;
    private javax.swing.JTextField departmentNameField;
    private javax.swing.JTextField departmentNameField2;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel educationLabel;
    private javax.swing.JPanel educationPanel;
    private javax.swing.JPanel experiencePanel;
    private javax.swing.JLabel experinceLabel;
    private javax.swing.JTextField finishDateField;
    private javax.swing.JTextField finishField;
    private javax.swing.JTextField gradeField;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jobField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField schoolNameField;
    private javax.swing.JTextField schoolNameField1;
    private javax.swing.JTextField startDateField;
    private javax.swing.JTextField startField;
    // End of variables declaration//GEN-END:variables
}
