/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package findjob;
import java.sql.*;
import java.text.DateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author BusraGural
 */
public class AccountPageUI extends javax.swing.JFrame {
    Connection conn;
    User currentUser;
    Education education = new Education();
    Experience experience = new Experience();
    Certificate certificate = new Certificate();
    
    private boolean edit = false;
    
    
    /**
     * Creates new form AccountPageUI
     */
    public AccountPageUI(Connection conn) {
        this.conn = conn;
        currentUser = LoginUI.currentUser;
        System.out.println("name2 " + currentUser.getUsername());
        initComponents();
        currentUser = currentUser.fetchUserDetails(conn, currentUser.getUsername());
        System.out.println("current userin idsi" + currentUser.getId());
        System.out.println("current userin adi : " + currentUser.getName());
        nameField.setText(currentUser.getName() + " " + currentUser.getSurname());
        if(!edit){
            Helpers.disableTextFields(jPanel1);        
        }
        education = education.getEducationDetails(conn, currentUser.getId(), education);
        setEducationFields();
        
        experience = experience.getExperienceDetails(conn, currentUser.getId(), experience);
        setExperienceFields();
        
        certificate = certificate.getCertificateDetails(conn, currentUser.getId(), certificate);
        setCertificateFields();
        
    }

    public void setEducationFields(){
        schoolNameField.setText(education.getSchoolName());
        departmentNameField.setText(education.getDepartment());
        gradeField.setText(Double.toString(education.getGrade()));
        
        LocalDate date = education.getStartDate();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String formattedDate = date.format(formatter);
        startDateField.setText(formattedDate);
        
        date = education.getFinishDate();
        formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        formattedDate = date.format(formatter);
        finishDateField.setText(formattedDate);
        
    }
    
    public void setExperienceFields(){
        companyNameField.setText(experience.getCompanyName());
        depNameField.setText(experience.getDepartment());
        jobField.setText(experience.getJobName());
        
        LocalDate date = experience.getStartDate();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String formattedDate = date.format(formatter);
        startField.setText(formattedDate);
        
        date = experience.getFinishDate();
        formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        formattedDate = date.format(formatter);
        finishField.setText(formattedDate);
        
       
    }
    
    public void setCertificateFields(){
          
        certifNameField.setText(certificate.getCertifName());
        LocalDate date = certificate.getReceiptDate();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String formattedDate = date.format(formatter);
        cstartField.setText(formattedDate);
        certCompanyField.setText(certificate.getCompanyName());
        durationField.setText(String.valueOf(certificate.getDuration()));
      
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        educationLabel = new javax.swing.JLabel();
        educationPanel = new javax.swing.JPanel();
        schoolNameField = new javax.swing.JTextField();
        departmentNameField = new javax.swing.JTextField();
        startDateField = new javax.swing.JTextField();
        finishDateField = new javax.swing.JTextField();
        gradeField = new javax.swing.JTextField();
        gradeLabel = new javax.swing.JLabel();
        eduEditButton = new javax.swing.JButton();
        eduAddButton = new javax.swing.JButton();
        experinceLabel = new javax.swing.JLabel();
        experiencePanel = new javax.swing.JPanel();
        companyNameField = new javax.swing.JTextField();
        depNameField = new javax.swing.JTextField();
        startField = new javax.swing.JTextField();
        finishField = new javax.swing.JTextField();
        jobField = new javax.swing.JTextField();
        expEditButton = new javax.swing.JButton();
        expAddButton = new javax.swing.JButton();
        certifLabel = new javax.swing.JLabel();
        certifPanel = new javax.swing.JPanel();
        certifNameField = new javax.swing.JTextField();
        cstartField = new javax.swing.JTextField();
        certCompanyField = new javax.swing.JTextField();
        certEditButton = new javax.swing.JButton();
        certAddButton = new javax.swing.JButton();
        durationLabel = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        receiveDateLabel = new javax.swing.JLabel();
        appLabel = new javax.swing.JLabel();
        appPanel = new javax.swing.JPanel();
        advTitle = new javax.swing.JTextField();
        advOwnerField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 231, 231));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel4.setBackground(new java.awt.Color(234, 231, 231));

        imagePanel.setBackground(new java.awt.Color(118, 179, 157));

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        nameField.setBackground(new java.awt.Color(231, 231, 231));
        nameField.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nameField.setForeground(new java.awt.Color(40, 55, 57));
        nameField.setText("AD SOYAD");
        nameField.setCaretColor(new java.awt.Color(3, 39, 103));
        nameField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        educationLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        educationLabel.setForeground(new java.awt.Color(40, 55, 57));
        educationLabel.setText("Eğitim");

        educationPanel.setBackground(new java.awt.Color(231, 231, 231));
        educationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        schoolNameField.setBackground(new java.awt.Color(231, 231, 231));
        schoolNameField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        schoolNameField.setForeground(new java.awt.Color(40, 55, 57));
        schoolNameField.setText("Üniversite Adı");
        schoolNameField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        schoolNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolNameFieldActionPerformed(evt);
            }
        });

        departmentNameField.setBackground(new java.awt.Color(231, 231, 231));
        departmentNameField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        departmentNameField.setForeground(new java.awt.Color(40, 55, 57));
        departmentNameField.setText("Bölüm Adı");
        departmentNameField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        departmentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentNameFieldActionPerformed(evt);
            }
        });

        startDateField.setBackground(new java.awt.Color(231, 231, 231));
        startDateField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        startDateField.setForeground(new java.awt.Color(40, 55, 57));
        startDateField.setText("Başlangıç Tarihi");
        startDateField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        startDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateFieldActionPerformed(evt);
            }
        });

        finishDateField.setBackground(new java.awt.Color(231, 231, 231));
        finishDateField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        finishDateField.setForeground(new java.awt.Color(40, 55, 57));
        finishDateField.setText("Bitiş Tarihi");
        finishDateField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        finishDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishDateFieldActionPerformed(evt);
            }
        });

        gradeField.setBackground(new java.awt.Color(231, 231, 231));
        gradeField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        gradeField.setForeground(new java.awt.Color(40, 55, 57));
        gradeField.setText("3.8");
        gradeField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        gradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeFieldActionPerformed(evt);
            }
        });

        gradeLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(39, 41, 50));
        gradeLabel.setText("Not Ortalaması:");

        eduEditButton.setBackground(new java.awt.Color(231, 231, 231));
        eduEditButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        eduEditButton.setForeground(new java.awt.Color(118, 179, 157));
        eduEditButton.setText("Düzenle");
        eduEditButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eduEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduEditButtonActionPerformed(evt);
            }
        });

        eduAddButton.setBackground(new java.awt.Color(231, 231, 231));
        eduAddButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        eduAddButton.setForeground(new java.awt.Color(118, 179, 157));
        eduAddButton.setText("Ekle");
        eduAddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eduAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout educationPanelLayout = new javax.swing.GroupLayout(educationPanel);
        educationPanel.setLayout(educationPanelLayout);
        educationPanelLayout.setHorizontalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addComponent(schoolNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(finishDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(gradeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gradeField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(602, 602, 602))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, educationPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eduAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eduEditButton))))
        );
        educationPanelLayout.setVerticalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eduEditButton)
                    .addComponent(eduAddButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeLabel)
                    .addComponent(gradeField))
                .addGap(15, 15, 15))
        );

        experinceLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        experinceLabel.setForeground(new java.awt.Color(40, 55, 57));
        experinceLabel.setText("Deneyim");

        experiencePanel.setBackground(new java.awt.Color(231, 231, 231));
        experiencePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        companyNameField.setBackground(new java.awt.Color(231, 231, 231));
        companyNameField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        companyNameField.setForeground(new java.awt.Color(40, 55, 57));
        companyNameField.setText("Kurum Adı");
        companyNameField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        companyNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameFieldActionPerformed(evt);
            }
        });

        depNameField.setBackground(new java.awt.Color(231, 231, 231));
        depNameField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        depNameField.setForeground(new java.awt.Color(40, 55, 57));
        depNameField.setText("Departman");
        depNameField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        depNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depNameFieldActionPerformed(evt);
            }
        });

        startField.setBackground(new java.awt.Color(231, 231, 231));
        startField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        startField.setForeground(new java.awt.Color(40, 55, 57));
        startField.setText("Başlangıç Tarihi");
        startField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        startField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startFieldActionPerformed(evt);
            }
        });

        finishField.setBackground(new java.awt.Color(231, 231, 231));
        finishField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        finishField.setForeground(new java.awt.Color(40, 55, 57));
        finishField.setText("Bitiş Tarihi");
        finishField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        finishField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishFieldActionPerformed(evt);
            }
        });

        jobField.setBackground(new java.awt.Color(231, 231, 231));
        jobField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jobField.setForeground(new java.awt.Color(40, 55, 57));
        jobField.setText("Meslek Adı");
        jobField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        jobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobFieldActionPerformed(evt);
            }
        });

        expEditButton.setBackground(new java.awt.Color(231, 231, 231));
        expEditButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        expEditButton.setForeground(new java.awt.Color(118, 179, 157));
        expEditButton.setText("Düzenle");
        expEditButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expEditButtonActionPerformed(evt);
            }
        });

        expAddButton.setBackground(new java.awt.Color(231, 231, 231));
        expAddButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        expAddButton.setForeground(new java.awt.Color(118, 179, 157));
        expAddButton.setText("Ekle");
        expAddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout experiencePanelLayout = new javax.swing.GroupLayout(experiencePanel);
        experiencePanel.setLayout(experiencePanelLayout);
        experiencePanelLayout.setHorizontalGroup(
            experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experiencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(experiencePanelLayout.createSequentialGroup()
                        .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(depNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(finishField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(experiencePanelLayout.createSequentialGroup()
                        .addComponent(jobField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, experiencePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(expAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expEditButton))
        );
        experiencePanelLayout.setVerticalGroup(
            experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experiencePanelLayout.createSequentialGroup()
                .addGroup(experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expEditButton)
                    .addComponent(expAddButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        certifLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        certifLabel.setForeground(new java.awt.Color(40, 55, 57));
        certifLabel.setText("Sertifikalar");

        certifPanel.setBackground(new java.awt.Color(231, 231, 231));
        certifPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        certifNameField.setBackground(new java.awt.Color(231, 231, 231));
        certifNameField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        certifNameField.setForeground(new java.awt.Color(40, 55, 57));
        certifNameField.setText("Sertifika Adı");
        certifNameField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        certifNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certifNameFieldActionPerformed(evt);
            }
        });

        cstartField.setBackground(new java.awt.Color(231, 231, 231));
        cstartField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cstartField.setForeground(new java.awt.Color(40, 55, 57));
        cstartField.setText("Başlangıç Tarihi");
        cstartField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        cstartField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstartFieldActionPerformed(evt);
            }
        });

        certCompanyField.setBackground(new java.awt.Color(231, 231, 231));
        certCompanyField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        certCompanyField.setForeground(new java.awt.Color(40, 55, 57));
        certCompanyField.setText("Kurum");
        certCompanyField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        certCompanyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certCompanyFieldActionPerformed(evt);
            }
        });

        certEditButton.setBackground(new java.awt.Color(231, 231, 231));
        certEditButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        certEditButton.setForeground(new java.awt.Color(118, 179, 157));
        certEditButton.setText("Düzenle");
        certEditButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        certEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certEditButtonActionPerformed(evt);
            }
        });

        certAddButton.setBackground(new java.awt.Color(231, 231, 231));
        certAddButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        certAddButton.setForeground(new java.awt.Color(118, 179, 157));
        certAddButton.setText("Ekle");
        certAddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        certAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certAddButtonActionPerformed(evt);
            }
        });

        durationLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        durationLabel.setForeground(new java.awt.Color(39, 41, 50));
        durationLabel.setText("Geçerlilik Süresi (yıl):");

        durationField.setBackground(new java.awt.Color(231, 231, 231));
        durationField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        durationField.setForeground(new java.awt.Color(40, 55, 57));
        durationField.setText("10");
        durationField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        durationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationFieldActionPerformed(evt);
            }
        });

        receiveDateLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        receiveDateLabel.setForeground(new java.awt.Color(39, 41, 50));
        receiveDateLabel.setText("Alınış Tarihi:");

        javax.swing.GroupLayout certifPanelLayout = new javax.swing.GroupLayout(certifPanel);
        certifPanel.setLayout(certifPanelLayout);
        certifPanelLayout.setHorizontalGroup(
            certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(certifPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(certifPanelLayout.createSequentialGroup()
                        .addComponent(certifNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(receiveDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cstartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(certifPanelLayout.createSequentialGroup()
                        .addComponent(certCompanyField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345)
                        .addComponent(durationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, certifPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(certAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(certEditButton))
        );
        certifPanelLayout.setVerticalGroup(
            certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(certifPanelLayout.createSequentialGroup()
                .addGroup(certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certEditButton)
                    .addComponent(certAddButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certifNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cstartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiveDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certCompanyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(durationLabel)
                        .addComponent(durationField)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        appLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        appLabel.setForeground(new java.awt.Color(40, 55, 57));
        appLabel.setText("Başvurularım");

        appPanel.setBackground(new java.awt.Color(231, 231, 231));
        appPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        advTitle.setBackground(new java.awt.Color(231, 231, 231));
        advTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        advTitle.setForeground(new java.awt.Color(40, 55, 57));
        advTitle.setText("İlan Başlığı");
        advTitle.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        advTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advTitleActionPerformed(evt);
            }
        });

        advOwnerField.setBackground(new java.awt.Color(231, 231, 231));
        advOwnerField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        advOwnerField.setForeground(new java.awt.Color(40, 55, 57));
        advOwnerField.setText("Kurum");
        advOwnerField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        advOwnerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advOwnerFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout appPanelLayout = new javax.swing.GroupLayout(appPanel);
        appPanel.setLayout(appPanelLayout);
        appPanelLayout.setHorizontalGroup(
            appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(advOwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        appPanelLayout.setVerticalGroup(
            appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advOwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(appPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(appLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(certifPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(experiencePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(experinceLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imagePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(educationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(educationLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(certifLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(131, 131, 131))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(educationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(educationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(experinceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(experiencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(certifLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(certifPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schoolNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolNameFieldActionPerformed

    private void departmentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentNameFieldActionPerformed

    private void startDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateFieldActionPerformed

    private void finishDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishDateFieldActionPerformed

    private void eduEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduEditButtonActionPerformed
        // TODO add your handling code here:
        edit = !edit;
        
        if(edit){
            Helpers.enableTextFields(educationPanel);
            eduEditButton.setText("Kaydet");
        }
        else{
            Helpers.disableTextFields(educationPanel);
            eduEditButton.setText("Düzenle");
            String schoolName = schoolNameField.getText();
            String departmentName = departmentNameField.getText();
            double grade = Double.parseDouble(gradeField.getText());
            String dateString = startDateField.getText();
            LocalDate startDate = Helpers.parseDate(dateString);
            dateString = finishDateField.getText();
            LocalDate finishDate = Helpers.parseDate(dateString);
            
            Education tmpEducation = new Education(currentUser.getId(), schoolName,departmentName, grade, startDate, finishDate);
            education.updateEducationDetails(conn, currentUser.getId(),tmpEducation );
            
        }
   
    }//GEN-LAST:event_eduEditButtonActionPerformed

    private void gradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeFieldActionPerformed

    private void companyNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameFieldActionPerformed

    private void depNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depNameFieldActionPerformed

    private void startFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startFieldActionPerformed

    private void finishFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishFieldActionPerformed

    private void jobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobFieldActionPerformed

    private void certifNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certifNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certifNameFieldActionPerformed

    private void cstartFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstartFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cstartFieldActionPerformed

    private void certCompanyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certCompanyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certCompanyFieldActionPerformed

    private void advTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advTitleActionPerformed

    private void advOwnerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advOwnerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advOwnerFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void expEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expEditButtonActionPerformed
        // TODO add your handling code here:
        edit = !edit;
        if(edit){
            Helpers.enableTextFields(experiencePanel);
            expEditButton.setText("Kaydet");
        }
        else{
            Helpers.disableTextFields(experiencePanel);
            expEditButton.setText("Düzenle");
            String companyName = companyNameField.getText();
            String depName = depNameField.getText();
            String jobName = jobField.getText();
            String dateString = startDateField.getText();
            LocalDate startDate = Helpers.parseDate(dateString);
            dateString = finishDateField.getText();
            LocalDate finishDate = Helpers.parseDate(dateString);
            
            Experience tmpExp = new Experience(currentUser.getId(),companyName, depName, jobName, startDate, finishDate);
            experience.updateExperienceDetails(conn,currentUser.getId() , tmpExp);
            
        }
    }//GEN-LAST:event_expEditButtonActionPerformed

    private void certEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certEditButtonActionPerformed
        // TODO add your handling code here:
        edit = !edit;
        if(edit){
            Helpers.enableTextFields(certifPanel);
            certEditButton.setText("Kaydet");
        }
        else{
            Helpers.disableTextFields(certifPanel);
            certEditButton.setText("Düzenle");
            String name = certifNameField.getText();
            int duration = Integer.parseInt(durationField.getText());
            String dateString = cstartField.getText();
            LocalDate startDate = Helpers.parseDate(dateString);
            String company = certCompanyField.getText();
            
            Certificate tmpCer = new Certificate(currentUser.getId(), name, company, duration, startDate);
            certificate.updateCertificateDetails(conn, currentUser.getId(), tmpCer);
            
        }
    }//GEN-LAST:event_certEditButtonActionPerformed

    private void eduAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduAddButtonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_eduAddButtonActionPerformed

    private void expAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expAddButtonActionPerformed

    private void certAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certAddButtonActionPerformed

    private void durationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Connection conn = null;
               
                new AccountPageUI(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advOwnerField;
    private javax.swing.JTextField advTitle;
    private javax.swing.JLabel appLabel;
    private javax.swing.JPanel appPanel;
    private javax.swing.JButton certAddButton;
    private javax.swing.JTextField certCompanyField;
    private javax.swing.JButton certEditButton;
    private javax.swing.JLabel certifLabel;
    private javax.swing.JTextField certifNameField;
    private javax.swing.JPanel certifPanel;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JTextField cstartField;
    private javax.swing.JTextField depNameField;
    private javax.swing.JTextField departmentNameField;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JButton eduAddButton;
    private javax.swing.JButton eduEditButton;
    private javax.swing.JLabel educationLabel;
    private javax.swing.JPanel educationPanel;
    private javax.swing.JButton expAddButton;
    private javax.swing.JButton expEditButton;
    private javax.swing.JPanel experiencePanel;
    private javax.swing.JLabel experinceLabel;
    private javax.swing.JTextField finishDateField;
    private javax.swing.JTextField finishField;
    private javax.swing.JTextField gradeField;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jobField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel receiveDateLabel;
    private javax.swing.JTextField schoolNameField;
    private javax.swing.JTextField startDateField;
    private javax.swing.JTextField startField;
    // End of variables declaration//GEN-END:variables
}
