/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package findjob;
import java.sql.*;
import java.text.DateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author BusraGural
 */
public class AccountPageUI extends javax.swing.JFrame {
    Connection conn;
    User currentUser;
    Education education = new Education();
    Experience experience = new Experience();
    Certificate certificate = new Certificate();
    ArrayList<Education > educationList;
    private boolean edit = false;
    private DefaultTableModel educationTableModel;
    
    /**
     * Creates new form AccountPageUI
     */
    public AccountPageUI(Connection conn) {
        this.conn = conn;
        
        
        
        currentUser = LoginUI.currentUser;
        System.out.println("name2 " + currentUser.getUsername());
        initComponents();
        currentUser = currentUser.fetchUserDetails(conn, currentUser.getUsername());
        System.out.println("current userin idsi" + currentUser.getId());
        System.out.println("current userin adi : " + currentUser.getName());
        nameField.setText(currentUser.getName() + " " + currentUser.getSurname());
        if(!edit){
            Helpers.disableTextFields(jPanel1);     
            Helpers.disableTableFields(eduTable);
        }
     
        
        educationList = new ArrayList<>();
        educationTableModel = new DefaultTableModel(new Object[]{"Okul Adı", "Bölüm adı", "Not Ortalaması", "Başlangıç Tarihi", "Bitiş Tarihi"}, 0);
        eduTable.setModel(educationTableModel);
        
        educationList = education.getEducationList(conn, currentUser.getId());
        setEducationFields(educationList);
        
        
//        experience = experience.getExperienceDetails(conn, currentUser.getId(), experience);
//        setExperienceFields();
//        
//        certificate = certificate.getCertificateDetails(conn, currentUser.getId(), certificate);
//        setCertificateFields();
        
    }
    int getEduId(int rowId){
        System.out.println("testete" + educationList.get(rowId).getId());
            return educationList.get(rowId).getId();
            
    }
    private void setEducationFields(ArrayList<Education> educationList){
       if (educationTableModel != null) {
            for (Education edu : educationList) {
                // Assume that the table has columns with appropriate names
                Object[] rowData = {                                             
                        edu.getSchoolName(),
                        edu.getDepartment(),
                        edu.getGrade(),
                        edu.getStartDate(),
                        edu.getFinishDate()
                };
                educationTableModel.addRow(rowData);
            }
       }       
    }
    

    
//    public void setExperienceFields(){
//        companyNameField.setText(experience.getCompanyName());
//        depNameField.setText(experience.getDepartment());
//        jobField.setText(experience.getJobName());
//        
//        LocalDate date = experience.getStartDate();
//        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
//        String formattedDate = date.format(formatter);
//        startField.setText(formattedDate);
//        
//        date = experience.getFinishDate();
//        formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
//        formattedDate = date.format(formatter);
//        finishField.setText(formattedDate);
//        
//       
//    }
    
//    public void setCertificateFields(){
//          
//        certifNameField.setText(certificate.getCertifName());
//        LocalDate date = certificate.getReceiptDate();
//        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
//        String formattedDate = date.format(formatter);
//        cstartField.setText(formattedDate);
//        certCompanyField.setText(certificate.getCompanyName());
//        durationField.setText(String.valueOf(certificate.getDuration()));
//      
//    }
//    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        educationLabel = new javax.swing.JLabel();
        educationPanel = new javax.swing.JPanel();
        eduEditButton = new javax.swing.JButton();
        eduAddButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        eduTable = new javax.swing.JTable();
        experinceLabel = new javax.swing.JLabel();
        experiencePanel = new javax.swing.JPanel();
        expEditButton = new javax.swing.JButton();
        expAddButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        expTable1 = new javax.swing.JTable();
        certifLabel = new javax.swing.JLabel();
        certifPanel = new javax.swing.JPanel();
        certEditButton = new javax.swing.JButton();
        certAddButton = new javax.swing.JButton();
        cerfTable = new javax.swing.JScrollPane();
        expTable = new javax.swing.JTable();
        appLabel = new javax.swing.JLabel();
        appPanel = new javax.swing.JPanel();
        cerfTable1 = new javax.swing.JScrollPane();
        expTable2 = new javax.swing.JTable();
        goAccountPanel = new javax.swing.JPanel();
        homeBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 231, 231));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel4.setBackground(new java.awt.Color(234, 231, 231));

        imagePanel.setBackground(new java.awt.Color(118, 179, 157));

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        nameField.setBackground(new java.awt.Color(231, 231, 231));
        nameField.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nameField.setForeground(new java.awt.Color(40, 55, 57));
        nameField.setText("AD SOYAD");
        nameField.setCaretColor(new java.awt.Color(3, 39, 103));
        nameField.setDisabledTextColor(new java.awt.Color(40, 55, 57));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        educationLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        educationLabel.setForeground(new java.awt.Color(40, 55, 57));
        educationLabel.setText("Eğitim");

        educationPanel.setBackground(new java.awt.Color(231, 231, 231));
        educationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        eduEditButton.setBackground(new java.awt.Color(231, 231, 231));
        eduEditButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        eduEditButton.setForeground(new java.awt.Color(118, 179, 157));
        eduEditButton.setText("Düzenle");
        eduEditButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eduEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduEditButtonActionPerformed(evt);
            }
        });

        eduAddButton.setBackground(new java.awt.Color(231, 231, 231));
        eduAddButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        eduAddButton.setForeground(new java.awt.Color(118, 179, 157));
        eduAddButton.setText("Ekle");
        eduAddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eduAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduAddButtonActionPerformed(evt);
            }
        });

        eduTable.setBackground(new java.awt.Color(234, 231, 231));
        eduTable.setForeground(new java.awt.Color(40, 55, 57));
        eduTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Üniversite Adı", "Bölüm Adı", "Başlangıç Tarihi", "Bitiş Tarihi", "Not Ortalaması"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(eduTable);

        javax.swing.GroupLayout educationPanelLayout = new javax.swing.GroupLayout(educationPanel);
        educationPanel.setLayout(educationPanelLayout);
        educationPanelLayout.setHorizontalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, educationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eduAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eduEditButton)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        educationPanelLayout.setVerticalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eduAddButton)
                    .addComponent(eduEditButton)))
        );

        experinceLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        experinceLabel.setForeground(new java.awt.Color(40, 55, 57));
        experinceLabel.setText("Deneyim");

        experiencePanel.setBackground(new java.awt.Color(231, 231, 231));
        experiencePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        expEditButton.setBackground(new java.awt.Color(231, 231, 231));
        expEditButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        expEditButton.setForeground(new java.awt.Color(118, 179, 157));
        expEditButton.setText("Düzenle");
        expEditButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expEditButtonActionPerformed(evt);
            }
        });

        expAddButton.setBackground(new java.awt.Color(231, 231, 231));
        expAddButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        expAddButton.setForeground(new java.awt.Color(118, 179, 157));
        expAddButton.setText("Ekle");
        expAddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expAddButtonActionPerformed(evt);
            }
        });

        expTable1.setBackground(new java.awt.Color(234, 231, 231));
        expTable1.setForeground(new java.awt.Color(40, 55, 57));
        expTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kurum Adı", "Departman", "Meslek Adı", "Başlangıç Tarihi", "Bitiş Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(expTable1);

        javax.swing.GroupLayout experiencePanelLayout = new javax.swing.GroupLayout(experiencePanel);
        experiencePanel.setLayout(experiencePanelLayout);
        experiencePanelLayout.setHorizontalGroup(
            experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experiencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, experiencePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(expAddButton)
                        .addGap(1, 1, 1)
                        .addComponent(expEditButton))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        experiencePanelLayout.setVerticalGroup(
            experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experiencePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expAddButton)
                    .addComponent(expEditButton)))
        );

        certifLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        certifLabel.setForeground(new java.awt.Color(40, 55, 57));
        certifLabel.setText("Sertifikalar");

        certifPanel.setBackground(new java.awt.Color(231, 231, 231));
        certifPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        certEditButton.setBackground(new java.awt.Color(231, 231, 231));
        certEditButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        certEditButton.setForeground(new java.awt.Color(118, 179, 157));
        certEditButton.setText("Düzenle");
        certEditButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        certEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certEditButtonActionPerformed(evt);
            }
        });

        certAddButton.setBackground(new java.awt.Color(231, 231, 231));
        certAddButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        certAddButton.setForeground(new java.awt.Color(118, 179, 157));
        certAddButton.setText("Ekle");
        certAddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        certAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certAddButtonActionPerformed(evt);
            }
        });

        expTable.setBackground(new java.awt.Color(234, 231, 231));
        expTable.setForeground(new java.awt.Color(40, 55, 57));
        expTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sertifika Adı", "Kurum", "Alınış Tarihi", "Geçerlilik Süresi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cerfTable.setViewportView(expTable);

        javax.swing.GroupLayout certifPanelLayout = new javax.swing.GroupLayout(certifPanel);
        certifPanel.setLayout(certifPanelLayout);
        certifPanelLayout.setHorizontalGroup(
            certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, certifPanelLayout.createSequentialGroup()
                .addGap(0, 580, Short.MAX_VALUE)
                .addComponent(certAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(certEditButton))
            .addComponent(cerfTable)
        );
        certifPanelLayout.setVerticalGroup(
            certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, certifPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerfTable, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(certifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certEditButton)
                    .addComponent(certAddButton)))
        );

        appLabel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        appLabel.setForeground(new java.awt.Color(40, 55, 57));
        appLabel.setText("Başvurularım");

        appPanel.setBackground(new java.awt.Color(231, 231, 231));
        appPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        expTable2.setBackground(new java.awt.Color(234, 231, 231));
        expTable2.setForeground(new java.awt.Color(40, 55, 57));
        expTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "İlan Başlığı", "Kurum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cerfTable1.setViewportView(expTable2);

        javax.swing.GroupLayout appPanelLayout = new javax.swing.GroupLayout(appPanel);
        appPanel.setLayout(appPanelLayout);
        appPanelLayout.setHorizontalGroup(
            appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
            .addGroup(appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(appPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cerfTable1)
                    .addContainerGap()))
        );
        appPanelLayout.setVerticalGroup(
            appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(appPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(appPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cerfTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        goAccountPanel.setBackground(new java.awt.Color(118, 179, 157));

        homeBttn.setBackground(new java.awt.Color(118, 179, 157));
        homeBttn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        homeBttn.setText("◀");
        homeBttn.setAlignmentY(0.0F);
        homeBttn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        homeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout goAccountPanelLayout = new javax.swing.GroupLayout(goAccountPanel);
        goAccountPanel.setLayout(goAccountPanelLayout);
        goAccountPanelLayout.setHorizontalGroup(
            goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );
        goAccountPanelLayout.setVerticalGroup(
            goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(goAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(appPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(appLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(certifPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(experiencePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(experinceLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imagePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(educationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(educationLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(certifLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(131, 131, 131))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(goAccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(educationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(educationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(experinceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(experiencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(certifLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(certifPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(appLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eduEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduEditButtonActionPerformed
        // TODO add your handling code here:
        edit = !edit;
        
        if(edit){
            Helpers.enableTextFields(educationPanel);
            Helpers.enableTableFields(eduTable);
            eduEditButton.setText("Kaydet");
        }
        else{
            Helpers.disableTextFields(educationPanel);
            Helpers.disableTableFields(eduTable);
            eduEditButton.setText("Düzenle");
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            int rowCount = eduTable.getRowCount();
            for (int row = 0; row < rowCount; row++) {
                String schoolName = (String) eduTable.getValueAt(row, 0);
                String departmentName = (String) eduTable.getValueAt(row, 1);
                Double grade = (Double) eduTable.getValueAt(row, 2);
                LocalDate startDate = (LocalDate) eduTable.getValueAt(row, 3);  // Corrected line
                LocalDate finishDate = (LocalDate) eduTable.getValueAt(row, 4);  // Corrected line

                Education tmpEducation = new Education(currentUser.getId(), schoolName,departmentName, grade, startDate, finishDate);
                education.updateEducationDetails(conn, currentUser.getId(),tmpEducation, getEduId(row));            
            }
        }
    }//GEN-LAST:event_eduEditButtonActionPerformed
    
    
    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void expEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expEditButtonActionPerformed
//        // TODO add your handling code here:
//        edit = !edit;
//        if(edit){
//            Helpers.enableTextFields(experiencePanel);
//            expEditButton.setText("Kaydet");
//        }
//        else{
//            Helpers.disableTextFields(experiencePanel);
//            expEditButton.setText("Düzenle");
//            String companyName = companyNameField.getText();
//            String depName = depNameField.getText();
//            String jobName = jobField.getText();
//            String dateString = startDateField.getText();
//            LocalDate startDate = Helpers.parseDate(dateString);
//            dateString = finishDateField.getText();
//            LocalDate finishDate = Helpers.parseDate(dateString);
//            
//            Experience tmpExp = new Experience(currentUser.getId(),companyName, depName, jobName, startDate, finishDate);
//            experience.updateExperienceDetails(conn,currentUser.getId() , tmpExp);
//            
//        }
    }//GEN-LAST:event_expEditButtonActionPerformed

    private void certEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certEditButtonActionPerformed
        // TODO add your handling code here:
//        edit = !edit;
//        if(edit){
//            Helpers.enableTextFields(certifPanel);
//            certEditButton.setText("Kaydet");
//        }
//        else{
//            Helpers.disableTextFields(certifPanel);
//            certEditButton.setText("Düzenle");
//            String name = certifNameField.getText();
//            int duration = Integer.parseInt(durationField.getText());
//            String dateString = cstartField.getText();
//            LocalDate startDate = Helpers.parseDate(dateString);
//            String company = certCompanyField.getText();
//            
//            Certificate tmpCer = new Certificate(currentUser.getId(), name, company, duration, startDate);
//            certificate.updateCertificateDetails(conn, currentUser.getId(), tmpCer);
//            
//        }
    }//GEN-LAST:event_certEditButtonActionPerformed

    private void eduAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduAddButtonActionPerformed
        // TODO add your handling code here:
      
       
    }//GEN-LAST:event_eduAddButtonActionPerformed

    private void expAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expAddButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_expAddButtonActionPerformed

    private void certAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certAddButtonActionPerformed

    private void homeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBttnActionPerformed
        // TODO add your handling code here:
        dispose();
        new AdvertisementUI(conn).setVisible(true);
    }//GEN-LAST:event_homeBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Connection conn = null;
               
                new AccountPageUI(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appLabel;
    private javax.swing.JPanel appPanel;
    private javax.swing.JScrollPane cerfTable;
    private javax.swing.JScrollPane cerfTable1;
    private javax.swing.JButton certAddButton;
    private javax.swing.JButton certEditButton;
    private javax.swing.JLabel certifLabel;
    private javax.swing.JPanel certifPanel;
    private javax.swing.JButton eduAddButton;
    private javax.swing.JButton eduEditButton;
    private javax.swing.JTable eduTable;
    private javax.swing.JLabel educationLabel;
    private javax.swing.JPanel educationPanel;
    private javax.swing.JButton expAddButton;
    private javax.swing.JButton expEditButton;
    private javax.swing.JTable expTable;
    private javax.swing.JTable expTable1;
    private javax.swing.JTable expTable2;
    private javax.swing.JPanel experiencePanel;
    private javax.swing.JLabel experinceLabel;
    private javax.swing.JPanel goAccountPanel;
    private javax.swing.JButton homeBttn;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
