/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package findjob;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author BusraGural
 */
public class AdvertisementUI extends javax.swing.JFrame {
    
    private Connection conn;
    Advertisement adv = new Advertisement();
    ArrayList<Advertisement> jobAdvertisements;
    /**
     * Creates new form AdvertisementUI
     */
    public AdvertisementUI(Connection conn) {
        this.jobAdvertisements = new ArrayList<>();
        this.conn = conn;
        initComponents();
        Helpers.disableTextFields(jPanel1);
        Helpers.enableTextFields(imagePanel);
        //jobAdv = jobAdv.getJobAdvertisementDetails(conn, jobAdv);
        jobAdvertisements = adv.getAllJobAdvertisements(conn);
        setjobAdvertisementFields();
        
        
    }
    
    
    void setjobAdvertisementFields(){
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        jobAdvButton = new javax.swing.JRadioButton();
        courseAdvButton = new javax.swing.JRadioButton();
        locationLabel = new javax.swing.JLabel();
        locationBox = new javax.swing.JComboBox<>();
        typeBox = new javax.swing.JComboBox<>();
        locationLabel1 = new javax.swing.JLabel();
        companyLabel = new javax.swing.JLabel();
        companyNameBox = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jobAdvPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        advTable = new javax.swing.JTable();
        detailButton = new javax.swing.JButton();
        filterPanel = new javax.swing.JPanel();
        submitFilterButton = new javax.swing.JButton();
        goAccountPanel = new javax.swing.JPanel();
        homeBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 231, 231));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel4.setBackground(new java.awt.Color(234, 231, 231));

        imagePanel.setBackground(new java.awt.Color(118, 179, 157));

        jobAdvButton.setBackground(new java.awt.Color(118, 179, 157));
        jobAdvButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jobAdvButton.setText("İş İlanları");

        courseAdvButton.setBackground(new java.awt.Color(118, 179, 157));
        courseAdvButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        courseAdvButton.setText("Kurs İlanları");

        locationLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        locationLabel.setText("Konum");

        locationBox.setBackground(new java.awt.Color(221, 221, 221));
        locationBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        locationBox.setForeground(new java.awt.Color(118, 179, 157));
        locationBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İstanbul", "Ankara", "Kayseri", "Çorum" }));

        typeBox.setBackground(new java.awt.Color(221, 221, 221));
        typeBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        typeBox.setForeground(new java.awt.Color(118, 179, 157));
        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tam Zamanlı", "Yarı Zamanlı", "Stajyer", " " }));

        locationLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        locationLabel1.setText("Job Type");

        companyLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        companyLabel.setText("Kurum");

        companyNameBox.setBackground(new java.awt.Color(221, 221, 221));
        companyNameBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        companyNameBox.setForeground(new java.awt.Color(118, 179, 157));
        companyNameBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monster" }));

        searchField.setBackground(new java.awt.Color(231, 231, 231));
        searchField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        searchField.setForeground(new java.awt.Color(40, 55, 57));

        searchButton.setBackground(new java.awt.Color(118, 179, 157));
        searchButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        searchButton.setText("🔍");
        searchButton.setAlignmentY(0.0F);
        searchButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchField)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addComponent(jobAdvButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseAdvButton)
                        .addGap(18, 18, 18)
                        .addComponent(locationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addComponent(locationLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(companyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobAdvButton)
                    .addComponent(courseAdvButton)
                    .addComponent(locationLabel)
                    .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyLabel)
                    .addComponent(companyNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationLabel1)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        nameLabel.setBackground(new java.awt.Color(234, 231, 231));
        nameLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(40, 55, 57));
        nameLabel.setText("İLANLAR");

        jobAdvPanel.setBackground(new java.awt.Color(231, 231, 231));
        jobAdvPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        submitButton.setBackground(new java.awt.Color(118, 179, 157));
        submitButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        submitButton.setForeground(new java.awt.Color(234, 231, 231));
        submitButton.setText("Başvur");

        advTable.setBackground(new java.awt.Color(234, 231, 231));
        advTable.setForeground(new java.awt.Color(40, 55, 57));
        advTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "İlan Adı", "Kurum Adı", "Konum", "Bitiş Tarihi", "Başvuran Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(advTable);

        detailButton.setBackground(new java.awt.Color(118, 179, 157));
        detailButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        detailButton.setForeground(new java.awt.Color(234, 231, 231));
        detailButton.setText("Detay");

        javax.swing.GroupLayout jobAdvPanelLayout = new javax.swing.GroupLayout(jobAdvPanel);
        jobAdvPanel.setLayout(jobAdvPanelLayout);
        jobAdvPanelLayout.setHorizontalGroup(
            jobAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobAdvPanelLayout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jobAdvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jobAdvPanelLayout.setVerticalGroup(
            jobAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobAdvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jobAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(detailButton))
                .addGap(13, 13, 13))
        );

        filterPanel.setBackground(new java.awt.Color(118, 179, 157));

        submitFilterButton.setBackground(new java.awt.Color(118, 179, 157));
        submitFilterButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        submitFilterButton.setText("✔");
        submitFilterButton.setAlignmentY(0.0F);
        submitFilterButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        submitFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFilterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(submitFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(submitFilterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        goAccountPanel.setBackground(new java.awt.Color(118, 179, 157));

        homeBttn.setBackground(new java.awt.Color(118, 179, 157));
        homeBttn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        homeBttn.setText("👤");
        homeBttn.setAlignmentY(0.0F);
        homeBttn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        homeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout goAccountPanelLayout = new javax.swing.GroupLayout(goAccountPanel);
        goAccountPanel.setLayout(goAccountPanelLayout);
        goAccountPanelLayout.setHorizontalGroup(
            goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );
        goAccountPanelLayout.setVerticalGroup(
            goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(goAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jobAdvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(599, 599, 599)
                        .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(goAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(8, 8, 8)
                .addComponent(jobAdvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBttnActionPerformed
        // TODO add your handling code here:
        dispose();
        new AccountPageUI(conn).setVisible(true);
    }//GEN-LAST:event_homeBttnActionPerformed

    private void submitFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitFilterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitFilterButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Connection conn = null;
                new AdvertisementUI(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable advTable;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JComboBox<String> companyNameBox;
    private javax.swing.JRadioButton courseAdvButton;
    private javax.swing.JButton detailButton;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel goAccountPanel;
    private javax.swing.JButton homeBttn;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jobAdvButton;
    private javax.swing.JPanel jobAdvPanel;
    private javax.swing.JComboBox<String> locationBox;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel locationLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton submitFilterButton;
    private javax.swing.JComboBox<String> typeBox;
    // End of variables declaration//GEN-END:variables
}
