/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package findjob;
import java.awt.GridLayout;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author BusraGural
 */
public class AdvertisementUI extends javax.swing.JFrame {
    
    private Connection conn;
    Advertisement adv = new Advertisement();
    ArrayList<Advertisement> jobAdvertisements;
    ArrayList<Advertisement> courseAdvertisements;
    ArrayList<Advertisement> filteredAdvertisements = new  ArrayList<>();
    private DefaultTableModel advJobTableModel;

    /**
     * Creates new form AdvertisementUI
     */
    public AdvertisementUI(Connection conn) {
        this.jobAdvertisements = new ArrayList<>();
        this.conn = conn;
        initComponents();
        Helpers.disableTextFields(jPanel1);
        Helpers.enableTextFields(imagePanel);
        Helpers.disableTableFields(advTable);
        
        advJobTableModel = new DefaultTableModel(new Object[]{"İlan Adı", "Kurum Adı", "Konum", "Bitiş Tarihi", "Başvuran Sayısı"}, 0);
        advTable.setModel(advJobTableModel);
        
        jobAdvertisements = adv.getAllJobAdvertisements(conn);
        setjobAdvertisementFields(jobAdvertisements);
        
        courseAdvertisements = adv.getAllCourseAdvertisements(conn);
       
    }
    
    
    void setjobAdvertisementFields(ArrayList<Advertisement> jobAdvertisements) {
        advJobTableModel.setRowCount(0);
        for (Advertisement adv : jobAdvertisements) {
            String name ="";
            try {
                name = adv.getCompanyNameById(conn, adv.getCompanyId());
            } catch (SQLException ex) {
                Logger.getLogger(AdvertisementUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            Object[] row = {
                    adv.getTitle(),
                    name, // Assuming there is a method like getCompanyName() in Advertisement class
                    adv.getLocation(),
                    adv.getDeadlineDate(), // Assuming getDeadlineDate() returns a formatted date
                    adv.getAppliedCount()
            };
            advJobTableModel.addRow(row);
        }

        advTable.setModel(advJobTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        jobAdvButton = new javax.swing.JRadioButton();
        courseAdvButton = new javax.swing.JRadioButton();
        locationLabel = new javax.swing.JLabel();
        locationBox = new javax.swing.JComboBox<>();
        typeBox = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        companyLabel = new javax.swing.JLabel();
        companyNameBox = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        workingTypeLabel = new javax.swing.JLabel();
        workTypeBox = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        jobAdvPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        advTable = new javax.swing.JTable();
        detailButton = new javax.swing.JButton();
        filterPanel = new javax.swing.JPanel();
        submitFilterButton = new javax.swing.JButton();
        goAccountPanel = new javax.swing.JPanel();
        homeBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 231, 231));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel4.setBackground(new java.awt.Color(234, 231, 231));

        imagePanel.setBackground(new java.awt.Color(118, 179, 157));

        jobAdvButton.setBackground(new java.awt.Color(118, 179, 157));
        buttonGroup2.add(jobAdvButton);
        jobAdvButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jobAdvButton.setText("İş İlanları");
        jobAdvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobAdvButtonActionPerformed(evt);
            }
        });

        courseAdvButton.setBackground(new java.awt.Color(118, 179, 157));
        buttonGroup2.add(courseAdvButton);
        courseAdvButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        courseAdvButton.setText("Kurs İlanları");
        courseAdvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseAdvButtonActionPerformed(evt);
            }
        });

        locationLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        locationLabel.setText("Konum");

        locationBox.setBackground(new java.awt.Color(221, 221, 221));
        locationBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        locationBox.setForeground(new java.awt.Color(118, 179, 157));
        locationBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "İstanbul", "Ankara", "Kayseri", "Çorum", " " }));

        typeBox.setBackground(new java.awt.Color(221, 221, 221));
        typeBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        typeBox.setForeground(new java.awt.Color(118, 179, 157));
        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "Tam Zamanlı", "Yarı Zamanlı", "Stajyer", " " }));

        typeLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        typeLabel.setText("Tür");

        companyLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        companyLabel.setText("Kurum");

        companyNameBox.setBackground(new java.awt.Color(221, 221, 221));
        companyNameBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        companyNameBox.setForeground(new java.awt.Color(118, 179, 157));
        companyNameBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "Monster", "Company4", " " }));

        searchField.setBackground(new java.awt.Color(231, 231, 231));
        searchField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        searchField.setForeground(new java.awt.Color(40, 55, 57));

        searchButton.setBackground(new java.awt.Color(118, 179, 157));
        searchButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        searchButton.setText("🔍");
        searchButton.setAlignmentY(0.0F);
        searchButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        workingTypeLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        workingTypeLabel.setText("Çalışma Şekli");

        workTypeBox.setBackground(new java.awt.Color(221, 221, 221));
        workTypeBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        workTypeBox.setForeground(new java.awt.Color(118, 179, 157));
        workTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "Remote", "Hibrit", "Yüzyüze", " " }));

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(locationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(typeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addComponent(companyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workingTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(workTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addGap(144, 144, 144)
                        .addComponent(jobAdvButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseAdvButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jobAdvButton)
                        .addComponent(courseAdvButton))
                    .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(workingTypeLabel)
                        .addComponent(workTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(companyLabel)
                            .addComponent(companyNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        nameLabel.setBackground(new java.awt.Color(234, 231, 231));
        nameLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(40, 55, 57));
        nameLabel.setText("İLANLAR");

        jobAdvPanel.setBackground(new java.awt.Color(231, 231, 231));
        jobAdvPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        submitButton.setBackground(new java.awt.Color(118, 179, 157));
        submitButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        submitButton.setForeground(new java.awt.Color(234, 231, 231));
        submitButton.setText("Başvur");

        advTable.setBackground(new java.awt.Color(234, 231, 231));
        advTable.setForeground(new java.awt.Color(40, 55, 57));
        advTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "İlan Adı", "Kurum Adı", "Konum", "Bitiş Tarihi", "Başvuran Sayısı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(advTable);

        detailButton.setBackground(new java.awt.Color(118, 179, 157));
        detailButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        detailButton.setForeground(new java.awt.Color(234, 231, 231));
        detailButton.setText("Detay");
        detailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jobAdvPanelLayout = new javax.swing.GroupLayout(jobAdvPanel);
        jobAdvPanel.setLayout(jobAdvPanelLayout);
        jobAdvPanelLayout.setHorizontalGroup(
            jobAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobAdvPanelLayout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jobAdvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jobAdvPanelLayout.setVerticalGroup(
            jobAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobAdvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jobAdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(detailButton))
                .addGap(13, 13, 13))
        );

        filterPanel.setBackground(new java.awt.Color(118, 179, 157));

        submitFilterButton.setBackground(new java.awt.Color(118, 179, 157));
        submitFilterButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        submitFilterButton.setText("✔");
        submitFilterButton.setAlignmentY(0.0F);
        submitFilterButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        submitFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFilterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(submitFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(submitFilterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        goAccountPanel.setBackground(new java.awt.Color(118, 179, 157));

        homeBttn.setBackground(new java.awt.Color(118, 179, 157));
        homeBttn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        homeBttn.setText("👤");
        homeBttn.setAlignmentY(0.0F);
        homeBttn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        homeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout goAccountPanelLayout = new javax.swing.GroupLayout(goAccountPanel);
        goAccountPanel.setLayout(goAccountPanelLayout);
        goAccountPanelLayout.setHorizontalGroup(
            goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );
        goAccountPanelLayout.setVerticalGroup(
            goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(goAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(goAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jobAdvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(599, 599, 599)
                        .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(goAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(8, 8, 8)
                .addComponent(jobAdvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBttnActionPerformed
        // TODO add your handling code here:
        dispose();
        new AccountPageUI(conn).setVisible(true);
    }//GEN-LAST:event_homeBttnActionPerformed

    private void submitFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitFilterButtonActionPerformed
        // TODO add your handling code here:
        boolean advSelected = true;
        
        if (jobAdvButton.isSelected()) {
            advSelected = true;
            System.out.println("Job Advertisement seçildi.");
        } else if (courseAdvButton.isSelected()) {
            advSelected = false;
            System.out.println("Course Advertisement seçildi.");
        } else {
            System.out.println("Hiçbiri seçilmedi.");
        }
        
        String selectedLocation = (String) locationBox.getSelectedItem();
        System.out.println(selectedLocation);
        String selectedType= (String) typeBox.getSelectedItem();
        System.out.println(selectedType);
        String selectedCompany= (String) companyNameBox.getSelectedItem();
        System.out.println(selectedCompany);
        
        
        int id = 0;
        try {
            id = adv.getCompanyIdByName(conn, selectedCompany);
        } catch (SQLException ex) {
            Logger.getLogger(AdvertisementUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String selectedWorkType = (String) workTypeBox.getSelectedItem();
        System.out.println(selectedWorkType);
        
        
        
        
        if(selectedCompany.compareTo("Hepsi") == 0 && selectedLocation.compareTo("Hepsi") == 0  && selectedType.compareTo("Hepsi") == 0 ){
            if(advSelected ){
                setjobAdvertisementFields(jobAdvertisements);
            }
            else{
                setjobAdvertisementFields(courseAdvertisements);
            }
        }
        else{
            filteredAdvertisements = adv.getFilteredAdvertisements(conn, advSelected, selectedLocation, selectedType, id, selectedWorkType);
            setjobAdvertisementFields(filteredAdvertisements);
        }
        
    }//GEN-LAST:event_submitFilterButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jobAdvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobAdvButtonActionPerformed
        // TODO add your handling code here:
        String[] newItems = {"Hepsi","Tam Zamanlı", "Yarı Zamanlı", "Stajyer"};
        typeBox.setModel(new DefaultComboBoxModel<>(newItems));
         workTypeBox.setEnabled(true);
    }//GEN-LAST:event_jobAdvButtonActionPerformed

    private void courseAdvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseAdvButtonActionPerformed
        // TODO add your handling code here:
        String[] newItems = {"Hepsi","Online", "Yüzyüze"};
        typeBox.setModel(new DefaultComboBoxModel<>(newItems));
        workTypeBox.setEnabled(false);
        
        
    }//GEN-LAST:event_courseAdvButtonActionPerformed

    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = advTable.getSelectedRow();

        // Ensure a row is selected
        if (selectedRow >= 0) {
            // Get the Advertisement object from the selected row
            Advertisement selectedAdvertisement = jobAdvertisements.get(selectedRow);

            // Show the details dialog
            showDetailDialog(selectedAdvertisement);
        } else {
            // No row is selected, you may want to handle this case (show an error message, for example)
            System.out.println("No row selected.");
        }
    }//GEN-LAST:event_detailButtonActionPerformed

    private void showDetailDialog(Advertisement adv) {
        JDialog detailDialog = new JDialog(new JFrame(), "Advertisement Details", true);
        detailDialog.setSize(600, 300);

        JPanel detailPanel = new JPanel(new GridLayout(6, 2, 10, 10));
        detailPanel.setBorder(new EmptyBorder(10, 10, 10, 10));

    //    detailPanel.add(new JLabel("Departman:"));
    //    detailPanel.add(new JLabel(adv.getDepartment()));

        detailPanel.add(new JLabel("İlan Adı:"));
        detailPanel.add(new JLabel(adv.getTitle()));

        detailPanel.add(new JLabel("Kurum Adı:"));
        try {
            String companyName = adv.getCompanyNameById(conn, adv.getCompanyId());
            detailPanel.add(new JLabel(companyName));
        } catch (SQLException ex) {
            detailPanel.add(new JLabel("Hata: " + ex.getMessage()));
        }


        JLabel descriptionLabel = new JLabel("Açıklama:");
        JTextArea descriptionTextArea = new JTextArea(adv.getDescription());
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setWrapStyleWord(true);
        descriptionTextArea.setEditable(false);
        JScrollPane descriptionScrollPane = new JScrollPane(descriptionTextArea);
        detailPanel.add(descriptionLabel);
        detailPanel.add(descriptionScrollPane);

        detailPanel.add(new JLabel("İlan Açılış Tarihi:"));
        detailPanel.add(new JLabel(adv.getOpenDate().toString()));

        detailPanel.add(new JLabel("Bitiş Tarihi:"));
        detailPanel.add(new JLabel(adv.getDeadlineDate().toString()));

        detailPanel.add(new JLabel("Çalışma Modeli:"));
        detailPanel.add(new JLabel(adv.getWorkingModel()));

        detailDialog.add(detailPanel);
        detailDialog.setLocationRelativeTo(null);
        detailDialog.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Connection conn = null;
                new AdvertisementUI(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable advTable;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JComboBox<String> companyNameBox;
    private javax.swing.JRadioButton courseAdvButton;
    private javax.swing.JButton detailButton;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel goAccountPanel;
    private javax.swing.JButton homeBttn;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jobAdvButton;
    private javax.swing.JPanel jobAdvPanel;
    private javax.swing.JComboBox<String> locationBox;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton submitFilterButton;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JComboBox<String> workTypeBox;
    private javax.swing.JLabel workingTypeLabel;
    // End of variables declaration//GEN-END:variables
}
